# Generated by Django 3.1.12 on 2025-08-19 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_successstory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='successstory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Success Story', 'verbose_name_plural': 'Success Stories'},
        ),
        migrations.RenameField(
            model_name='successstory',
            old_name='story',
            new_name='content',
        ),
        migrations.AddField(
            model_name='successstory',
            name='category',
            field=models.CharField(blank=True, choices=[('career', 'Career Growth'), ('business', 'Business & Entrepreneurship'), ('personal', 'Personal Development'), ('health', 'Health & Fitness'), ('education', 'Education & Learning'), ('creative', 'Creative Pursuits'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='successstory',
            name='celebrations_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='successstory',
            name='hearts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='successstory',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='successstory',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=300),
        ),
        migrations.AddField(
            model_name='successstory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StoryReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('heart', 'Heart'), ('celebration', 'Celebration')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.successstory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'story', 'reaction_type')},
            },
        ),
    ]
