# Generated by Django 5.2.5 on 2025-09-03 22:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250819_2320'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storyreaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='StudyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of your study notes', max_length=200)),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('cs', 'Computer Science'), ('ds', 'Data Structures'), ('algorithms', 'Algorithms'), ('web', 'Web Development'), ('ml', 'Machine Learning'), ('db', 'Databases'), ('os', 'Operating Systems'), ('networking', 'Networking'), ('other', 'Other')], help_text='Subject of the notes', max_length=20)),
                ('topic', models.CharField(blank=True, help_text='Specific topic (e.g., Binary Search)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the notes')),
                ('file', models.FileField(help_text='Upload PDF, DOCX, or image files', upload_to='study_notes/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail image', null=True, upload_to='note_thumbnails/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Whether the note is approved for sharing')),
                ('is_public', models.BooleanField(default=True, help_text='Whether the note is visible to all users')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Note',
                'verbose_name_plural': 'Study Notes',
                'ordering': ['-upload_date'],
            },
        ),
    ]
