# Generated by Django 5.2.5 on 2025-09-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contact_id_alter_storyreaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynote',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
